name: Bug Report
description: File a bug report for this project
title: ":bug: "
labels: ["kind/bug"]
projects: ["xunleii/2"]

body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please search existing issues.

        ----

        Thank you for filing a bug report! Please fill out the sections below to help us reproduce the bug.

  - type: textarea
    id: what_happened
    attributes:
      label: ":fire: What happened?"
      description: Describe the issue you are experiencing here
    validations:
      required: true
  - type: textarea
    id: what_expected
    attributes:
      label: ":+1: What did you expect to happen?"
      description: Describe what you expected to happen here
    validations:
      required: false
  - type: textarea
    id: how_reproduce
    attributes:
      label: ":mag: How can we reproduce the issue?"
      description: Describe how to reproduce the problem in as much detail as possible
    validations:
      required: true

  - type: input
    id: module_version
    attributes:
      label: ":wrench: Module version"
      description: Please provide the version of the module you are using
    validations:
      required: true
  - type: input
    id: terraform_version
    attributes:
      label: ":wrench: Terraform version"
      description: Please provide the version of Terraform you are using
    validations:
      required: true

  - type: textarea
    id: provider_list
    attributes:
      label: ":wrench: Terraform providers"
      description: List all the providers you are using with their version (copy the output of `terraform providers`)
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: ":clipboard: Additional information"
      description: Please provide any additional information that might be useful
    validations:
      required: false
