name: Security hardening (Terraform)

on:
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquasecurity/trivy-action@3d1b5be1589a83fc98b82781c263708b2eb3b47b # 0.16.1
        with:
          scan-type: config
          scan-ref: .
          exit-code: 1
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
