name: Security hardening (Github Actions workflows)

on:
  pull_request:
    types: [opened, synchronize]
    paths: [".github/workflows/**"]

jobs:
  ci_harden_security:
    name: Github Action security hardening
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Lint your Github Actions
        run: |
          curl -O https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json

          echo "::add-matcher::actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@70c4af2ed5282c51ba40566d026d6647852ffa3e # v5.0.1
