name: Terraform plan validation (PRs only)

on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write

jobs:
  examples_hcloud-k3s:
    name: Hetzner Cloud
    if: ${{ github.event.label.name == 'terraform:plan' }}
    permissions:
      pull-requests: write
    secrets:
      env: |
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    uses: ./.github/workflows/templates.terraform.pull_requests.plan.yaml
    with:
      terraform_vars: |
        ssh_key: ''
      terraform_workdir: examples/hcloud-k3s

  unlabel-pull-request:
    if: always()
    name: Remove 'terraform:plan' label
    needs: [examples_hcloud-k3s]
    runs-on: ubuntu-latest
    steps:
      - name: Unlabel 'terraform:plan'
        uses: actions-ecosystem/action-remove-labels@d05162525702062b6bdef750ed8594fc024b3ed7
        with:
          labels: terraform:plan
